version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /apps/client
      - /apps/desktop
      - /apps/server
      - /packages/plugin-sdk
      - /packages/shared
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: cargo
    directory: /apps/desktop/sidecar
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore(deps)"
